Repository wix/react-native-ui-lib, pull requests merged in 2020-06, with the labels that each got.

#799 [Bug] Passing validate prop to input as array makes that input required
  src/components/inputs/BaseInput.js
Labels: bug

#802 [Feature] Added handling of array of undefined validations
  src/components/inputs/BaseInput.js
Labels: feature request

#809 Refactor typography presets code
  generatedTypes/components/button/index.d.ts
  generatedTypes/style/typography.d.ts
  generatedTypes/style/typographyPresets.d.ts
  src/style/typography.ts
  src/style/typographyPresets.ts
Labels: WIP

#833 Fix some types, add exports for components `Props` types
  src/commons/asBaseComponent.tsx
  src/components/checkbox/index.tsx
  src/components/radioButton/RadioButton.tsx
  src/components/radioButton/RadioGroup.tsx
  src/index.ts
  typings/commons/index.d.ts
Labels: typescript
