Repository wix/react-native-ui-lib, pull requests merged in 2020-07, with the labels that each got.

#834 Fix button static values and other small type fixes
  generatedTypes/commons/asBaseComponent.d.ts
  generatedTypes/components/button/index.d.ts
  generatedTypes/components/card/CardImage.d.ts
  generatedTypes/components/card/CardSection.d.ts
  generatedTypes/components/card/index.d.ts
  generatedTypes/components/checkbox/index.d.ts
  generatedTypes/components/image/index.d.ts
  generatedTypes/components/radioButton/RadioButton.d.ts
  generatedTypes/components/radioButton/RadioGroup.d.ts
  generatedTypes/components/text/index.d.ts
  generatedTypes/components/touchableOpacity/index.d.ts
  generatedTypes/components/view/index.d.ts
  generatedTypes/incubator/TouchableOpacity.d.ts
  generatedTypes/index.d.ts
  src/components/button/index.tsx
  src/components/card/CardImage.tsx
  src/index.ts
  typings/commons/index.d.ts
Labels: typescript

#836 Add prop types:`backgroundColor` to `View` and `animate` to `Carousel`
  generatedTypes/components/view/index.d.ts
  src/components/view/index.tsx
  typings/components/Carousel.d.ts
Labels: typescript

#838 Expose some ts props to outside
  generatedTypes/index.d.ts
  src/index.ts
  typings/components/TagsInput.d.ts
Labels: typescript

#845 KeyboardInput - rename RCTCustomKeyboardViewController --> RCTCustomKeyboardViewControllerTemp
  lib/ios/reactnativeuilib.xcodeproj/project.pbxproj
  lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomInputControllerTemp.m
  lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomKeyboardViewControllerTemp.h
  lib/ios/reactnativeuilib/keyboardinput/rctcustomInputcontroller/RCTCustomKeyboardViewControllerTemp.m
  lib/package.json
Labels: WIP

#846 Adding 'react-native-community/picker' dependency
  lib/components/WheelPicker/index.js
  package.json
Labels: pending
