Repository wix/react-native-ui-lib, pull requests merged in 2021-11, with the labels that each got.

#1490 Feat/chips input v2
  demo/src/screens/componentScreens/ChipsInputScreen.js
  demo/src/screens/componentScreens/ChipsInputScreen.tsx
  generatedTypes/index.d.ts
  generatedTypes/src/components/chipsInput/Presenter.d.ts
  generatedTypes/src/components/chipsInput/index.d.ts
  generatedTypes/src/incubator/TextField/usePreset.d.ts
  src/components/chipsInput/Presenter.ts
  src/components/chipsInput/__tests__/index.spec.js
  src/components/chipsInput/index.js
  src/components/chipsInput/index.tsx
  src/index.ts
  typings/components/ChipsInput.d.ts
Labels: pending

#1619 Drawer - block frame update for missing items
  src/components/drawer/Swipeable.tsx
Labels: Important for Next Release

#1661 Fix misuse of new event emitter API in useOrientation hook
  src/hooks/useOrientation/index.ts
Labels: Important for Next Release

#1632 Infra/picker expandable overlay
  demo/src/screens/componentScreens/PickerScreen.js
  demo/src/screens/incubatorScreens/IncubatorExpandableOverlayScreen.tsx
  generatedTypes/src/incubator/expandableOverlay/index.d.ts
  src/components/picker/PickerModal.js
  src/components/picker/__tests__/index.spec.js
  src/components/picker/index.js
  src/incubator/expandableOverlay/index.tsx
Labels: Important for Next Release

#1649 fix picker multi value
  src/components/picker/index.js
Labels: Important for Next Release

#1659 Fix issue with TextField hint is missing when using floatingPlaceholder
  generatedTypes/src/incubator/TextField/Presenter.d.ts
  generatedTypes/src/incubator/TextField/usePreset.d.ts
  src/incubator/TextField/Presenter.ts
  src/incubator/TextField/__tests__/Presenter.spec.js
  src/incubator/TextField/index.tsx
Labels: Important for Next Release

#1669 Feat/text highlight refactor
  generatedTypes/src/components/text/index.d.ts
  generatedTypes/src/utils/index.d.ts
  generatedTypes/src/utils/textUtils.d.ts
  src/.babelrc.json
  src/components/text/__tests__/index.spec.js
  src/components/text/index.tsx
  src/utils/__tests__/textUtils.spec.js
  src/utils/index.ts
  src/utils/textUtils.ts
  tsconfig.json
Labels: Important for Next Release

#1674 TextField - fix placeholder memoization
  src/components/textField/index.js
Labels: Important for Next Release

#1639 Use react-freeze to optimize TabController pages
  demo/src/screens/componentScreens/TabControllerScreen/index.tsx
  demo/src/screens/componentScreens/TabControllerScreen/tab3.tsx
  package.json
  src/components/tabController/TabPage.tsx
Labels: Important for Next Release

#1673 Drawer - fix leftToggle for RTL
  src/components/drawer/Swipeable.tsx
Labels: Important for Next Release

#1697 Fix issue with editable prop not working on Picker component
  generatedTypes/src/incubator/expandableOverlay/index.d.ts
  src/components/picker/__tests__/index.spec.js
  src/components/picker/index.js
  src/incubator/expandableOverlay/index.tsx
Labels: Important for Next Release, hotfix

#1681 Feat/new chips input
  demo/src/screens/MenuStructure.js
  demo/src/screens/incubatorScreens/IncubatorChipsInputScreen.tsx
  demo/src/screens/incubatorScreens/index.js
  generatedTypes/src/incubator/ChipsInput/index.d.ts
  generatedTypes/src/incubator/index.d.ts
  src/incubator/ChipsInput/assets/xSmall.png
  src/incubator/ChipsInput/assets/xSmall@1.5x.png
  src/incubator/ChipsInput/assets/xSmall@2x.png
  src/incubator/ChipsInput/assets/xSmall@3x.png
  src/incubator/ChipsInput/assets/xSmall@4x.png
  src/incubator/ChipsInput/chipsInput.api.json
  src/incubator/ChipsInput/index.tsx
  src/incubator/TextField/index.tsx
  src/incubator/index.ts
Labels: Important for Next Release
