Repository wix/react-native-ui-lib, pull requests merged in 2022-05, with the labels that each got.

#2030 Infra/picker new file
  src/components/picker/NativePicker.js
  src/components/picker/PickerDialog.android.js
  src/components/picker/PickerDialog.js
  src/components/picker/__tests__/index.spec.js
  src/components/picker/index.js
  src/components/picker/index.tsx
  src/index.ts
Labels: Important for Next Release, hotfix

#2032 Infra/ update and add tokens
  src/style/designTokens.ts
  src/style/designTokensDM.ts
Labels: Important for Next Release

#2059 Carousel - fix initial page
  src/components/carousel/index.tsx
Labels: Important for Next Release

#2060 Dialog (old) - add static directions
  demo/src/screens/componentScreens/DialogScreen.js
  src/components/dialog/index.tsx
Labels: Important for Next Release

#2068 Dialog (old) - add export for DialogDirections
  src/components/dialog/index.tsx
  src/index.ts
Labels: hotfix

#2070 Picker.Item - expose isItemDisabled
  src/components/picker/PickerItem.tsx
  src/components/picker/types.tsx
Labels: Important for Next Release
