Repository wix/react-native-ui-lib, pull requests merged in 2023-05, with the labels that each got.

#2542 Replacing 'react-native-text-size' with wix fork
  ios/rnuilib.xcodeproj/project.pbxproj
  package.json
  src/style/typography.ts
Labels: Important for Next Release

#2585 Enable TS check on demo files and fix all errors
  demo/src/screens/PlaygroundScreen.tsx
  demo/src/screens/componentScreens/ActionBarScreen.tsx
  demo/src/screens/componentScreens/AvatarsScreen.tsx
  demo/src/screens/componentScreens/BasicListScreen.tsx
  demo/src/screens/componentScreens/ButtonsScreen.tsx
  demo/src/screens/componentScreens/CarouselScreen.tsx
  demo/src/screens/componentScreens/ChipsInputScreen.tsx
  demo/src/screens/componentScreens/ColorPickerScreen.tsx
  demo/src/screens/componentScreens/DrawerScreen.tsx
  demo/src/screens/componentScreens/GridViewScreen.tsx
  demo/src/screens/componentScreens/HintsScreen.tsx
  demo/src/screens/componentScreens/ModalScreen.tsx
  demo/src/screens/componentScreens/OverlaysScreen.tsx
  demo/src/screens/componentScreens/PanDismissibleScreen.tsx
  demo/src/screens/componentScreens/PanListenerScreen.tsx
  demo/src/screens/componentScreens/ScrollBarScreen.tsx
  demo/src/screens/componentScreens/SectionsWheelPickerScreen.tsx
  demo/src/screens/componentScreens/SliderScreen.tsx
  demo/src/screens/componentScreens/TabControllerScreen/index.tsx
  demo/src/screens/componentScreens/TextFieldScreen.tsx
  demo/src/screens/componentScreens/WheelPickerScreen.tsx
  demo/src/screens/componentScreens/WizardScreen.tsx
  demo/src/screens/incubatorScreens/IncubatorExpandableOverlayScreen.tsx
  demo/src/screens/incubatorScreens/IncubatorSliderScreen.tsx
  demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
  demo/src/screens/realExamples/Pinterest/index.tsx
  demo/src/screens/realExamples/ProductPage/index.tsx
  demo/src/screens/realExamples/Twitter/index.tsx
  src/commons/modifiers.ts
  src/components/avatar/index.tsx
  src/components/button/ButtonTypes.tsx
  src/components/button/index.tsx
  src/components/card/index.tsx
  src/components/chip/index.tsx
  src/components/icon/index.tsx
  src/components/image/index.tsx
  src/components/modal/TopBar.tsx
  src/components/picker/index.tsx
  src/incubator/TouchableOpacity.tsx
  src/incubator/index.ts
  src/incubator/toast/types.ts
  src/index.ts
  src/utils/imageUtils.ts
  tsconfig.dev.json
  typings/globalTypes.d.ts
Labels: Important for Next Release, hotfix

#2593 Move to reanimated 3
  android/app/src/main/java/com/rnuilib/MainApplication.java
  demo/src/screens/incubatorScreens/IncubatorToastScreen.tsx
  demo/src/screens/incubatorScreens/TouchableOpacityScreen.js
  package.json
  src/components/sortableList/SortableListItem.tsx
Labels: hotfix

#2598 Incubator.Slider - fix onValueChange throttle
  src/components/colorPicker/ColorPickerDialog.tsx
  src/incubator/Slider/index.tsx
Labels: Important for Next Release

#2561 Feat/ SortableList - add ItemMargin prop
  src/components/sortableList/SortableList.api.json
  src/components/sortableList/SortableListContext.ts
  src/components/sortableList/SortableListItem.tsx
  src/components/sortableList/index.tsx
  src/components/sortableList/types.ts
Labels: Important for Next Release
