Repository wix/react-native-ui-lib, pull requests merged in 2023-10, with the labels that each got.

#2760 DynamicFonts - add isFontFamilyDownloaded
  lib/components/DynamicFonts/index.ts
Labels: Important for Next Release

#2740 [WEB] Allow pass id to SvgImage
  src/components/svgImage/index.web.tsx
Labels: Important for Next Release

#2771 Fix react-native.config has wrong file for DynamicFont
  react-native.config.js
Labels: hotfix

#2775 Feat/indication for mandatory field
  src/incubator/TextField/FieldContext.ts
  src/incubator/TextField/Label.tsx
  src/incubator/TextField/__tests__/index.spec.js
  src/incubator/TextField/index.tsx
  src/incubator/TextField/textField.api.json
  src/incubator/TextField/types.ts
  src/incubator/TextField/useFieldState.ts
Labels: TextField

#2787 PickerItem - support asynchronous and ignore selection
  src/components/picker/PickerItem.tsx
  src/components/picker/types.tsx
Labels: Important for Next Release
