Repository wix/react-native-ui-lib, pull requests merged in 2024-03, with the labels that each got.

#2968 Incubator.Slider - fix track layout when values change
  src/incubator/Slider/index.tsx
Labels: hotfix

#2970 Icon - fix wrapper breaks alignment (center modifier)
  src/components/icon/index.tsx
Labels: hotfix

#2971 GradientSlider - fix thumbTintColor override
  src/components/slider/GradientSlider.tsx
  src/components/slider/context/asSliderGroupChild.tsx
Labels: hotfix

#2978 TextInput - keyboardType="number-pad" with external keyboard
  lib/ios/reactnativeuilib/keyboardtrackingview/ObservingInputAccessoryViewTemp.m
  lib/package.json
Labels: Important for Next Release

#2983 Image support in string as source, for svg strings
  src/components/icon/index.tsx
  src/components/image/index.tsx
  src/utils/__tests__/imageUtils.spec.js
  src/utils/imageUtils.ts
Labels: hotfix

#2988 Incubator Slider - fix step interpolation
  src/incubator/Slider/SliderPresenter.ts
Labels: Important for Next Release, hotfix
