Repository wix/react-native-ui-lib, pull requests merged in 2024-05, with the labels that each got.

#2909 Fixed dialog test to actually test for existence
  src/incubator/Dialog/__tests__/index.new.spec.tsx
Labels: wontfix

#3064 Use rowGap and columnGap feature in our GridList and SortableGridList…
  src/components/gridList/index.tsx
  src/components/gridList/types.ts
  src/components/gridList/useGridLayout.ts
  src/components/sortableGridList/index.tsx
Labels: Important for Next Release

#3096 Fix/segmented control icon spacings
  src/components/segmentedControl/segment.tsx
Labels: Important for Next Release

#3078 deprecate children, migrate picker props
  src/components/picker/helpers/usePickerMigrationWarnings.tsx
  src/components/picker/index.tsx
  src/components/picker/types.tsx
Labels: Important for Next Release

#3103 avoid passing columnWrapperStyle when numberOfColumns is 1
  src/components/gridList/index.tsx
Labels: hotfix
