Repository wix/react-native-ui-lib, pull requests merged in 2025-04, with the labels that each got.

#3688 TabController - tix RTL in Android
  src/components/tabController/useScrollToItem.ts
Labels: hotfix

#3701 Enhance note display in PropsList with improved note section styling …
  docuilib/src/components/pageComponents/PropsList.tsx
Labels: docs

#3696 Picker - useWheelPicker fix accessibility
  src/components/WheelPicker/Item.tsx
  src/components/picker/PickerItemsList.tsx
  src/components/picker/index.tsx
Labels: Important for Next Release

#3703 figma embed removed footer
  docuilib/package.json
  docuilib/src/components/pageComponents/ContentItem.tsx
Labels: waiting-for-response
