Repository wix/react-native-ui-lib, pull requests merged in 2025-03, with the labels that each got.

#3547 Button Accessibility hit target - Fixed hit slop overriding.
  demo/src/screens/__tests__/__snapshots__/TextFieldScreen.spec.js.snap
  src/components/button/index.tsx
Labels: waiting-for-response

#3541 Fix issue with hint targetFrame prop
  demo/src/screens/componentScreens/HintsScreen.tsx
  src/components/hint/hooks/useHintLayout.ts
Labels: hotfix, waiting-for-response

#3579 Added jsx rendering in docs
  docuilib/src/components/pageComponents/ContentItem.tsx
  src/components/test.api.json
Labels: docs

#3596 Timeline - fix api json
  src/components/timeline/timeline.api.json
Labels: Important for Next Release, waiting-for-response

#3611 Docs - Timeline - fix live components
  docuilib/package.json
  src/components/timeline/timeline.api.json
Labels: waiting-for-response

#3531 Slider - Increased hit target
  src/incubator/slider/Thumb.tsx
Labels: waiting-for-response

#3559 Documentation - Direct link to props in props list
  docuilib/src/components/ComponentPage.tsx
  docuilib/src/components/pageComponents/PropsList.tsx
Labels: waiting-for-response

#3614 Docs - Toast Live Preview
  docuilib/src/components/pageComponents/ContentItem.tsx
  docuilib/src/theme/ReactLiveScope/index.js
  src/incubator/toast/toast.api.json
Labels: waiting-for-response

#3542 add ellipsizeMode prop for text truncation and improve accessibility
  demo/src/screens/__tests__/__snapshots__/AvatarScreen.spec.js.snap
  src/components/avatar/index.tsx
Labels: waiting-for-response

#3635 Infra/assets internal new structure
  docuilib/package.json
  docuilib/src/theme/ReactLiveScope/configurations.ts
  docuilib/src/theme/ReactLiveScope/index.js
  package.json
  scripts/assets/extractDimensions.js
  src/assets/internal/icons/index.web.js
  src/assets/internal/images/index.web.js
  src/components/icon/index.tsx
  webDemo/webpack.config.js
Labels: docs

#3640 Docs site redesign fixes
  docuilib/package.json
  docuilib/src/css/custom.css
  docuilib/src/theme/Footer/index.tsx
  docuilib/static/img/logo_rnui.png
Labels: waiting-for-response
